### PR TITLE
Controller & Service method to edit an animal, bugfix in Add animal f…

### PR DESCRIPTION
**Pull request by kkaniewski**
…orm(cancel button was actually adding a new empty Pet record to the list)

### CODE REVIEW

**Comment by Evirth** [comment]
There's some bug when you choose English language. On each page it shows "Title" instead of suitable name for example "Add Pet" ;)

**Comment by kkaniewski** [comment]
I've seen that. Quite got no idea why it happens, but I'll try to fix it somehow.

**Comment by Evirth** [comment]
Oh I even didn't notice it before 😂

**Comment by kkaniewski** [comment]
Fixed

**Pull request merged**
